import pandas as pd
import glob
import os
import numpy as np

def load_latest_results():
    """Finds and loads the most recent IPO typo results CSV."""
    list_of_files = glob.glob('data/ipo_study_*/ipo_typo_results.csv')
    if not list_of_files:
        print("No result files found in data/ipo_study_*/")
        return None
    latest_file = max(list_of_files, key=os.path.getctime)
    print(f"Loading results from: {latest_file}")
    return pd.read_csv(latest_file)

def compute_alpha(df, vol_threshold=3.0, price_spike_threshold=0.02):
    """
    Computes performance metrics for a strategy that buys on Open and sells on High
    when volume buying pressure is detected.
    """
    print(f"\n--- Strategy Configuration ---")
    print(f"Trigger Condition: Volume Spike > {vol_threshold}x AND Intraday High > {price_spike_threshold*100}%")
    
    # 1. Identify Trades
    # We only 'trade' if the volume indicates 'increased buying pressure'
    # In a real-time scenario, we'd see volume pace accelerating. 
    # Here, we use the daily relative volume as a proxy for that pressure.
    trades = df[
        (df['Volume_Spike_Ratio'] > vol_threshold) & 
        (df['Intraday_High_Pct'] > price_spike_threshold)
    ].copy()
    
    if trades.empty:
        print("No trades met the criteria.")
        return

    print(f"Number of Trades Executed: {len(trades)} (out of {len(df)} monitored events)")

    # 2. Calculate Returns for different Execution Scenarios
    
    # Scenario A: "Perfect Top Tick" - Buy Open, Sell High
    # Represents the theoretical maximum Alpha available to be captured.
    trades['Return_Max_Potential'] = (trades['Typo_High'] - trades['Typo_Open']) / trades['Typo_Open']
    
    # Scenario B: "Reversion Reality" - Buy Open, Sell Close
    # What happens if you hold too long and it reverts?
    trades['Return_Hold_Close'] = (trades['Typo_Close'] - trades['Typo_Open']) / trades['Typo_Open']
    
    # Scenario C: "Realistic Capture" - Assume we capture 50% of the spike
    # We sell at the average of Open and High
    trades['Return_Realistic'] = ((trades['Typo_High'] + trades['Typo_Open']) / 2 - trades['Typo_Open']) / trades['Typo_Open']

    # 3. Aggregate Metrics
    metrics = {
        'Scenario': ['Max Potential (Sell High)', 'Realistic (Capture 50% of Spike)', 'Reversion (Hold to Close)'],
        'Total_Return': [
            trades['Return_Max_Potential'].sum(),
            trades['Return_Realistic'].sum(),
            trades['Return_Hold_Close'].sum()
        ],
        'Avg_Return_Per_Trade': [
            trades['Return_Max_Potential'].mean(),
            trades['Return_Realistic'].mean(),
            trades['Return_Hold_Close'].mean()
        ],
        'Win_Rate': [
            (trades['Return_Max_Potential'] > 0).mean(),
            (trades['Return_Realistic'] > 0).mean(),
            (trades['Return_Hold_Close'] > 0).mean()
        ],
        'Max_Win': [
            trades['Return_Max_Potential'].max(),
            trades['Return_Realistic'].max(),
            trades['Return_Hold_Close'].max()
        ],
        'Max_Loss': [
            trades['Return_Max_Potential'].min(), # Should be 0 for buy open sell high unless High < Open (impossible)
            trades['Return_Realistic'].min(),
            trades['Return_Hold_Close'].min()
        ]
    }
    
    results_df = pd.DataFrame(metrics)
    
    # Format for display
    results_df['Total_Return'] = results_df['Total_Return'].map('{:.2%}'.format)
    results_df['Avg_Return_Per_Trade'] = results_df['Avg_Return_Per_Trade'].map('{:.2%}'.format)
    results_df['Win_Rate'] = results_df['Win_Rate'].map('{:.2%}'.format)
    results_df['Max_Win'] = results_df['Max_Win'].map('{:.2%}'.format)
    results_df['Max_Loss'] = results_df['Max_Loss'].map('{:.2%}'.format)
    
    print("\n--- Performance Report ---")
    print(results_df.to_string(index=False))
    
    print("\n--- Top Winning Trades (Max Potential) ---")
    top_wins = trades.sort_values(by='Return_Max_Potential', ascending=False).head(5)
    print(top_wins[['IPO_Date', 'IPO_Ticker', 'Typo_Ticker', 'Volume_Spike_Ratio', 'Return_Max_Potential']].to_string(index=False))

    print("\n--- Worst Reversion Trades (Hold to Close) ---")
    # Trades that popped high but closed low (validating the need to sell early)
    reversions = trades.sort_values(by='Reversion_From_High_Pct', ascending=True).head(5)
    print(reversions[['IPO_Date', 'IPO_Ticker', 'Typo_Ticker', 'Intraday_High_Pct', 'Reversion_From_High_Pct', 'Return_Hold_Close']].to_string(index=False))

def main():
    df = load_latest_results()
    if df is not None:
        # We assume alpha is generated by selecting strictly those with high volume
        # We test thresholds: >3x avg volume and at least 2% intraday move
        compute_alpha(df, vol_threshold=3.0, price_spike_threshold=0.02)

if __name__ == "__main__":
    main()
